version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env   # 👈 Usa tu archivo .env con la URI de Atlas
    volumes:
      - ./backend:/app
    command: npm run dev



volumes:
  mongo-data: